# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 几一的网络日志
email: jiyifun@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a slow walker, but I never walk backwards.
baseurl: "/jiyiblogs" # the subpath of your site, e.g. /blog
url: "http://shuzi156.github.io" # the base hostname & protocol for your site
github_username:  shuzi156

# Build settings
markdown: kramdown
